rollout_type: ofa

## ---- Component search_space ----
# ---- Type ofa ----
search_space_type: ofa
search_space_cfg:
  num_cell_groups: [1, 4, 4, 4, 4, 4]
  expansions: [1, 6, 6, 6, 6, 6]
  schedule_cfg:
    kernel_choice:
        type: value
        boundary: [1, 81]
        value: [[7, 5], [7, 5, 3]]
    width_choice:
      type: value
      boundary: [1, 161, 241]
      value: [[6], [6, 4], [6, 4, 3]]
    depth_choice:
      type: value
      boundary: [1, 321, 401]
      value: [[4], [4, 3], [4, 3, 2]]
# ---- End Type mnsanet_ofa ----
## ---- End Component search_space ----

## ---- Component dataset ----
dataset_type: coco
dataset_cfg:
  load_train_only: false
  random_choose: false
  random_seed: 123
  train_crop_size: 300
  test_crop_size: 300
# ---- End Type cifar10 ----
## ---- End Component dataset ----

## ---- Component controller ----
# ---- Type rl ----
controller_type: ofa
controller_cfg:
  # Schedulable attributes:
  rollout_type: ofa
# ---- End Type rl ----
## ---- End Component controller ----

## ---- Component evaluator ----
# ---- Type mepa ----
evaluator_type: mepa
evaluator_cfg:
  # Schedulable attributes: controller_surrogate_steps, mepa_surrogate_steps, mepa_samples
  load_optimizer: false
  load_scheduler: false
  rollout_type: ofa
  batch_size: 48
  controller_surrogate_steps: 0
  # derive_surrogate_steps: 0
  mepa_surrogate_steps: 0
  mepa_optimizer:
    lr: 0.005
    momentum: 0.9
    type: SGD
    weight_decay: 0.0001
  mepa_scheduler:
    eta_min: 0.0
    T_max: 80
    type: CosineAnnealingLR
  surrogate_optimizer: null
  surrogate_scheduler: null
  mepa_samples: 1
  data_portion:
  - 0.0
  - 1. # train evaluator weights
  - 0. # for train controller
  mepa_as_surrogate: false
  bptt_steps: 35
  schedule_cfg: null
  workers_per_queue: 8
# ---- End Type mepa ----
## ---- End Component evaluator ----

## ---- Component weights_manager ----
# ---- Type supernet ----
weights_manager_type: det_supernet
weights_manager_cfg:
  # Schedulable attributes: 
  rollout_type: ofa
  search_backbone_type: ofa_supernet
  search_backbone_cfg:
    backbone_type: mbv3_backbone
    backbone_cfg:
      blocks: [1, 4, 4, 4, 4, 4]
      strides: [1, 2, 2, 2, 1, 2]
      expansions: [1, 6, 6, 6, 6, 6]
      acts: ["relu", "relu", "relu", "h_swish", "h_swish", "h_swish"]
      layer_channels: [16, 16, 24, 40, 80, 112, 160, 960, 1280]
      mult_ratio: 1.
      kernel_sizes: [3, 5, 7]
      num_classes: 90
      block_type: mbv3_block
      pretrained_path: null

  head_type: ssd_head_final_model
  head_cfg:
    expansions: [0.5, 0.5, 0.5, 0.5]
    channels: [512, 256, 256, 128]
    aspect_ratios: [[2, 3], [2, 3], [2, 3], [2, 3], [2], [2]]
  num_classes: 91
  feature_levels: [4, 5]
  
# ---- End Type supernet ----
## ---- End Component weights_manager ----

objective_type: ssd_detection
objective_cfg:
  # Schedulable attributes:
  num_classes: 91
  nms_threshold: 0.3
  clip: true
  aspect_ratios: [[2, 3], [2, 3], [2, 3], [2, 3], [2], [2]]
#   latency_file: latency_block.txt

## ---- Component trainer ----
# ---- Type simple ----
trainer_type: simple
trainer_cfg:
  # Schedulable attributes: controller_samples, derive_samples
  rollout_type: ofa
  epochs: 500
  test_every: 50
  controller_scheduler: null
  controller_samples: 1
  derive_samples: 1
  evaluator_steps: null
  controller_steps: 0
  controller_train_every: 1
  controller_train_begin: 1001
  interleave_controller_every: null
  schedule_cfg: null
# ---- End Type simple ----
## ---- End Component trainer ----
