rollout_type: ofa

## ---- Component search_space ----
# ---- Type ofa ----
search_space_type: ofa
search_space_cfg:
  num_cell_groups: [1, 4, 4, 4, 4, 4]
  expansions: [1, 6, 6, 6, 6, 6]
  schedule_cfg:
    width_choice:
      type: value
      boundary: [1, 60, 120]
      value: [[6], [6,5,4], [6,5,4,3,2]]
    depth_choice:
      type: value
      boundary: [1, 180, 240]
      value: [[4], [4,3], [4,3,2]]
# ---- End Type mnsanet_ofa ----
## ---- End Component search_space ----

## ---- Component dataset ----
# ---- Type cifar10 ----
dataset_type: coco
dataset_cfg:
  load_train_only: false
  random_choose: false
  random_seed: 123
  train_crop_size: 300
  test_crop_size: 300
  # image_mean: [123, 116, 103]
  # image_std: 1.
  # image_norm_factor: 1.
  # image_bias: 0.
# ---- End Type cifar10 ----
## ---- End Component dataset ----

## ---- Component controller ----
# ---- Type rl ----
controller_type: ofa
controller_cfg:
  # Schedulable attributes:
  rollout_type: mbv3_ofa
  force_uniform: true
# ---- End Type rl ----
## ---- End Component controller ----

## ---- Component evaluator ----
# ---- Type mepa ----
evaluator_type: mepa
evaluator_cfg:
  # Schedulable attributes: controller_surrogate_steps, mepa_surrogate_steps, mepa_samples
  load_optimizer: false
  load_scheduler: false
  rollout_type: ofa
  batch_size: 128
  controller_surrogate_steps: 0
  # derive_surrogate_steps: 0
  mepa_surrogate_steps: 0
  mepa_optimizer:
    lr: 0.05
    momentum: 0.9
    type: SGD
    weight_decay: 0.0001
  mepa_scheduler:
    eta_min: 0.0
    T_max: 500
    type: CosineAnnealingLR
  surrogate_optimizer: null
  surrogate_scheduler: null
  mepa_samples: 1
  data_portion:
  - 0.0
  - 0.8 # train evaluator weights
  - 0.2 # for train controller
  mepa_as_surrogate: false
  bptt_steps: 35
  schedule_cfg: null
# ---- End Type mepa ----
## ---- End Component evaluator ----

## ---- Component weights_manager ----
# ---- Type supernet ----
weights_manager_type: ofa_supernet
weights_manager_cfg:
  # Schedulable attributes:
  rollout_type: ofa
# ---- End Type supernet ----
## ---- End Component weights_manager ----

objective_type: detection
objective_cfg:
  # Schedulable attributes:
  num_classes: 90
  anchors_generator_type: ssd_anchors_generator
  anchors_generator_cfg:
    min_dim: 300
    aspect_ratios: [[2, 3], [2, 3], [2, 3], [2, 3], [2], [2]]
    feature_maps: [19, 10, 5, 3, 2, 1]
    scales: [45, 90, 135, 180, 225, 270, 315]
    steps: [16, 32, 64, 100, 150, 300]
    clip: true
  matcher_type: iou_matcher
  matcher_cfg:
    matched_threshold: 0.5
    unmatched_threshold: 0.5
    variance: [0.1, 0.2]
  loss_type: multibox_loss
  loss_cfg:
    neg_mining: true
    neg_pos: 3
  post_processing_type: ssd_post_processing
  post_processing_cfg:
    top_k: 200
    confidence_threshold: 0.01
    nms_threshold: 0.5
    variance: [0.1, 0.2]
    apply_prob_type: "softmax"
  # latency_coeff: 1.0
#   latency_file: latency_block.txt

## ---- Component trainer ----
# ---- Type simple ----
trainer_type: simple
trainer_cfg:
  # Schedulable attributes: controller_samples, derive_samples
  rollout_type: ofa
  epochs: 500
  test_every: 1
  controller_scheduler: null
  controller_samples: 1
  derive_samples: 8
  evaluator_steps: null
  controller_steps: 0
  controller_train_every: 1
  controller_train_begin: 1001
  interleave_controller_every: null
  schedule_cfg: null
# ---- End Type simple ----
## ---- End Component trainer ----

final_model_type: ssd_final_model
final_model_cfg:
  num_classes: 90
  backbone_type: ofa_final_model
  backbone_cfg:
    genotypes: "cell_0=1,cell_1=4,cell_2=4,cell_3=4,cell_4=4,cell_5=4, cell_0_block_0=(1, 3),cell_1_block_0=(6, 7),cell_1_block_1=(6, 7),cell_1_block_2=(6, 7), cell_1_block_3=(6, 7), cell_2_block_0=(6, 7),cell_2_block_1=(6, 7),cell_2_block_2=(6, 7),cell_2_block_3=(6, 7),cell_3_block_0=(6, 7),cell_3_block_1=(6, 7),cell_3_block_2=(6, 7),cell_3_block_3=(6, 7),cell_4_block_0=(6, 7),cell_4_block_1=(6, 7),cell_4_block_2=(6, 7),cell_4_block_3=(6, 7),cell_5_block_0=(6, 7),cell_5_block_1=(6, 7),cell_5_block_2=(6, 7),cell_5_block_3=(6, 7)"
    backbone_type: mbv3_backbone
    backbone_cfg:
      layer_channels: [16, 16, 24, 40, 80, 112, 160, 960, 1280]
      strides: [1, 2, 2, 2, 1, 2]
      mult_ratio: 1.
      kernel_sizes: [3, 5, 7]
  head_type: ssd_head_final_model
  head_cfg:
    expansions: [0.5, 0.5, 0.5, 0.5]
    channels: [512, 256, 256, 128]
    aspect_ratios: [[2, 3], [2, 3], [2, 3], [2, 3], [2], [2]]


final_trainer_type: det_final_trainer
final_trainer_cfg:
  batch_size: 32
  epochs: 200
  optimizer_scheduler:
    eta_min: 0.0
    T_max: 200
    type: CosineAnnealingLR
  schedule_cfg: null
  weight_decay: 0.0001
  learning_rate: 0.001
  momentum: 0.9
  freeze_base_net: false
  base_net_lr: 0.0005
  save_as_state_dict: true
  eval_every: 10