rollout_type: ofa

## ---- Component search_space ----
# ---- Type ofa ----
search_space_type: ofa
search_space_cfg:
  num_cell_groups: [1, 4, 4, 4, 4, 4]
  expansions: [1, 6, 6, 6, 6, 6]
  image_size_choice: [32]
  schedule_cfg:
    kernel_choice:
        type: value
        boundary: [1, 51, 120]
        value: [[7], [7, 5], [7, 5, 3]]
    width_choice:
      type: value
      boundary: [1, 180, 240]
      value: [[6], [6,5,4], [6,5,4,3,2]]
    depth_choice:
      type: value
      boundary: [1, 300, 360]
      value: [[4], [4, 3], [4,3,2]]
# ---- End Type mnsanet_ofa ----
## ---- End Component search_space ----

## ---- Component dataset ----
# ---- Type cifar100 ----
dataset_type: cifar100
dataset_cfg:
  # Schedulable attributes:
  cutout: null
# ---- End Type cifar100 ----
## ---- End Component dataset ----

## ---- Component controller ----
# ---- Type rl ----
controller_type: ofa
controller_cfg:
  # Schedulable attributes:
  rollout_type: ofa
# ---- End Type rl ----
## ---- End Component controller ----

## ---- Component evaluator ----
# ---- Type mepa ----
evaluator_type: mepa
evaluator_cfg:
  # Schedulable attributes: controller_surrogate_steps, mepa_surrogate_steps, mepa_samples
  load_optimizer: false
  load_scheduler: false
  rollout_type: ofa
  batch_size: 256
  controller_surrogate_steps: 0
  # derive_surrogate_steps: 0
  mepa_surrogate_steps: 0
  mepa_optimizer:
    lr: 0.05
    momentum: 0.97
    type: SGD
    weight_decay: 0.00004
  mepa_scheduler:
    eta_min: 0.0
    T_max: 500
    type: CosineAnnealingLR
  surrogate_optimizer: null
  surrogate_scheduler: null
  mepa_samples: 1
  data_portion:
  - 0.0
  - 1.0 # train evaluator weights
  - 0.0 # for train controller
  mepa_as_surrogate: false
  bptt_steps: 35
  schedule_cfg: null
  multiprocess: false
# ---- End Type mepa ----
## ---- End Component evaluator ----

## ---- Component weights_manager ----
# ---- Type supernet ----
weights_manager_type: ofa_supernet
weights_manager_cfg:
  # Schedulable attributes:
  rollout_type: ofa
  backbone_type: mbv3_backbone
  backbone_cfg:
    blocks: [1, 4, 4, 4, 4, 4]
    strides: [1, 2, 1, 2, 1, 1]
    expansions: [1, 6, 6, 6, 6, 6]
    layer_channels: [16, 16, 24, 40, 80, 112, 160, 960, 1280]
    mult_ratio: 1.
    kernel_sizes: [3, 5, 7]
    num_classes: 100
    block_type: mbv3_block
    stem_stride: 1
  multiprocess: false
# ---- End Type supernet ----
## ---- End Component weights_manager ----

objective_type: ofa_classification
objective_cfg:
  # Schedulable attributes:
  schedule_cfg:
    soft_loss_coeff:
      type: value
      boundary: [1, 60]
      value: [0.0, 6.0]
  soft_loss_coeff: 0.0
  latency_coeff: 1.0
  expect_latency: 20
  reward: mult
  punishment: hard
#   latency_file: latency_block.txt

## ---- Component trainer ----
# ---- Type simple ----
trainer_type: simple
trainer_cfg:
  # Schedulable attributes: controller_samples, derive_samples
  rollout_type: ofa
  epochs: 500
  test_every: 10
  controller_scheduler: null
  controller_samples: 1
  derive_samples: 8
  evaluator_steps: null
  controller_steps: 0
  controller_train_every: 1
  controller_train_begin: 1001
  interleave_controller_every: null
  schedule_cfg: null
# ---- End Type simple ----
## ---- End Component trainer ----
