# param: 11.2 M
# flops: 1110 M
# clean acc with aux head 0.4: 0.947

## ---- Component search_space ----
# ---- Type cnn ----
search_space_type: cnn
search_space_cfg:
  # Schedulable attributes: 
  cell_layout: [0, 0, 0, 1, 0, 0, 1, 0, 0]
  # cell_layout: [0, 0, 0, 1, 0, 0]
  num_cell_groups: 2
  num_init_nodes: 1
  num_layers: 9
  num_node_inputs: 1
  num_steps: 1
  reduce_cell_groups:
  - 1
  shared_primitives: # this is not used
  - none
 
# ---- End Type cnn ----
## ---- End Component search_space ----

## ---- Component dataset ----
# ---- Type cifar10 ----
dataset_type: cifar10
dataset_cfg:
  # Schedulable attributes: 
  cutout: null
# ---- End Type cifar10 ----
## ---- End Component dataset ----

## ---- Component final_model ----
# ---- Type cnn_genotype ----
final_model_type: cnn_final_model
final_model_cfg:
  # Schedulable attributes: dropout_path_rate
  # genotypes: "normal_0=[('xnor_resnet_block_pool_downsample', 0, 1)], reduce_1=[('xnor_resnet_block_pool_downsample', 0, 1)]"
  genotypes: "normal_0=[('dorefa_resnet_block', 0, 1)], reduce_1=[('dorefa_resnet_block', 0, 1)]"
  auxiliary_cfg: null
  auxiliary_head: False
  layer_channels: [16, 16, 16, 16, 32, 32, 32, 64, 64, 64]
  # layer_channels: [16, 16, 16, 16, 32, 32, 32]
  dropout_path_rate: 0.0
  dropout_rate: 0.0
  init_channels: 16
  num_classes: 10
  cell_use_preprocess: false
  schedule_cfg: null
  stem_multiplier: 1
  use_stem: conv_bn_relu_3x3
  stem_stride: 1
  stem_affine: true
# ---- End Type cnn_genotype ----
## ---- End Component final_model ----

objective_type: classification
objective_cfg: {}

## ---- Component final_trainer ----
# ---- Type cnn_trainer ----
final_trainer_type: cnn_trainer
final_trainer_cfg:
  # Schedulable attributes: 
  # auxiliary_head: true
  # auxiliary_weight: 0.4
  auxiliary_head: False
  auxiliary_weight: 0.4
  add_regularization: false
  batch_size: 128
  epochs: 300
  # grad_clip: 5.0
  learning_rate: 0.1
  momentum: 0.9
  no_bias_decay: false
  # optimizer_type: Adam
  optimizer_scheduler:
    # eta_min: 0.00
    # T_max: 300
    # type: CosineAnnealingLR
    type: MultiStepLR
    milestones: [100, 150, 180]
    gamma: 0.1
  schedule_cfg: null
  warmup_epochs: 0
  weight_decay: 1.e-4
  save_as_state_dict: true
# ---- End Type cnn_trainer ----
## ---- End Component final_trainer ----
